[workspace]
members = ["core", "ui", "app"]
resolver = "3"

[workspace.package]
version = "0.0.0"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
edition = "2024"
repository = "https://github.com/Jacobbishopxy/gpui-kbar"
