[package]
name = "app"
version.workspace = true
edition.workspace = true

[dependencies]
core = { path = "../core" }
ui = { path = "../ui" }
gpui.workspace = true
clap.workspace = true
anyhow.workspace = true
time.workspace = true

[[bin]]
name = "app-runtime"
path = "src/runtime.rs"
