[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
core = { path = "../core" }
gpui.workspace = true
gpui-component.workspace = true
time.workspace = true
anyhow.workspace = true
csv = "1.3"
